FROM debian:12.11
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root/workspace
COPY . .
RUN apt-get update && apt-get install -y locales && locale-gen en_US.UTF-8 && \
    apt-get install -y --no-install-recommends apt-utils && \
    apt-get upgrade -y && chmod +x install.sh
CMD ["bash"]
