version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -t dertin/debian-nginx-php:ci -f Dockerfile .
      - run: docker run -t --privileged=true --name container_test dertin/debian-nginx-php:ci /bin/bash -c "/root/workspace/install.sh"
      - run: docker start container_test
      - run: docker ps -a
      - run: docker exec -t container_test openssl version
      - run: docker exec -t container_test cmake --version
      - run: docker exec -t container_test curl -V
      - run: docker exec -t container_test python3 --version
      - run: docker exec -t container_test pip3 --version
      - run: docker exec -t container_test php -v
      - run: docker exec -t container_test php -i | grep 'Client API version'
      - run: docker exec -t container_test nginx -v
      - run: docker exec -t container_test service php-fpm start
      - run: docker exec -t container_test service nginx start
      - run: docker exec -t container_test certbot --version
      - run: docker stop container_test
      - run: docker rm $(docker ps -a -q)
workflows:
  build:
    jobs:
      - test
