version: 2.1
jobs:
  test-scratch:
    machine: true
    steps:
      - checkout
      - run: docker build -t dertin/debian-nginx-php:ci -f Dockerfile.testScratch .
      - run: docker run -t --privileged=true --name container_test_scratch dertin/debian-nginx-php:ci /bin/bash -c "/root/workspace/install.sh travis Y"
      - run: docker start container_test_scratch
      - run: docker ps -a
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/bin/openssl version"
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/local/bin/cmake --version"
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/local/bin/curl -V"
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/local/bin/python3 --version"
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/local/bin/python3 -m pip -V"
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/local/php/bin/php -v"
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/local/php/bin/php -i | grep 'Client API version'"
      - run: docker exec -t container_test_scratch /bin/bash -c "/usr/sbin/nginx -v"
      - run: docker exec -t container_test_scratch /bin/bash -c "service php-fpm start"
      - run: docker exec -t container_test_scratch /bin/bash -c "service nginx start"
      - run: docker exec -t container_test_scratch /bin/bash -c "certbot --version"
      - run: docker stop container_test_scratch
      - run: docker rm $(docker ps -a -q)
  test-buster:
    machine: true
    steps:
      - checkout
      - run: docker build -t dertin/debian-nginx-php:ci -f Dockerfile.testBuster .
      - run: docker run -t --privileged=true --name container_test_buster dertin/debian-nginx-php:ci /bin/bash -c "/root/workspace/install.sh travis Y"
      - run: docker start container_test_buster
      - run: docker ps -a
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/bin/openssl version"
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/local/bin/cmake --version"
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/local/bin/curl -V"
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/local/bin/python3 --version"
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/local/bin/python3 -m pip -V"
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/local/php/bin/php -v"
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/local/php/bin/php -i | grep 'Client API version'"
      - run: docker exec -t container_test_buster /bin/bash -c "/usr/sbin/nginx -v"
      - run: docker exec -t container_test_buster /bin/bash -c "service php-fpm start"
      - run: docker exec -t container_test_buster /bin/bash -c "service nginx start"
      - run: docker exec -t container_test_buster /bin/bash -c "certbot --version"
      - run: docker stop container_test_buster
      - run: docker rm $(docker ps -a -q)
workflows:
  build:
    jobs:
      - test-scratch
      - test-buster
